version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - freecodecamp
    volumes:
      - /Users/claire/fow/fow-be/trigger.sql:/docker-entrypoint-initdb.d/trigger.sql
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - freecodecamp
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    # volumes:
    #   - redis:/data
    # labels:
    #   - "name=redis"
    #   - "mode=standalone"
    # restart: always
    # command: redis-server /usr/local/conf/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
    networks:
      - freecodecamp
networks:
  freecodecamp:
